import { HeroSection } from '@/components/home/HeroSection';
import { NewsletterSignup } from '@/components/home/NewsletterSignup';
import { Separator } from '@/components/ui/separator';
import Image from 'next/image';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Star, Compass, BookOpen } from 'lucide-react';

const features = [
  {
    icon: <Star className="w-8 h-8 text-accent" />,
    title: "AI-Powered Insights",
    description: "Receive personalized tarot interpretations generated by advanced AI, tailored to your unique questions.",
    dataAiHint: "AI technology"
  },
  {
    icon: <Compass className="w-8 h-8 text-accent" />,
    title: "Explore Your Path",
    description: "Choose from various spreads like 1-card, 3-card, or custom layouts to delve into specific areas of your life.",
    dataAiHint: "tarot spread"
  },
  {
    icon: <BookOpen className="w-8 h-8 text-accent" />,
    title: "Tarot Encyclopedia",
    description: "Deepen your understanding of tarot with our comprehensive guide to card meanings, keywords, and symbolism.",
    dataAiHint: "ancient book"
  }
];


export default function HomePage() {
  return (
    <div className="space-y-16 sm:space-y-24">
      <HeroSection />
      
      <section className="py-16">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="font-headline text-3xl sm:text-4xl font-semibold text-primary">Why Choose MysticSight Tarot?</h2>
            <p className="mt-4 text-lg text-foreground/80 max-w-2xl mx-auto">
              We blend ancient wisdom with modern technology to offer you a unique and insightful tarot experience.
            </p>
          </div>
          <div className="grid md:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <Card key={index} className="shadow-lg hover:shadow-xl transition-shadow duration-300 bg-card/80 backdrop-blur-sm border-primary/10 animate-slide-up" style={{animationDelay: `${index * 0.15}s`}}>
                <CardHeader className="items-center text-center">
                  <div className="p-4 bg-accent/10 rounded-full mb-4 inline-block">
                    {feature.icon}
                  </div>
                  <CardTitle className="font-headline text-2xl text-primary">{feature.title}</CardTitle>
                </CardHeader>
                <CardContent className="text-center">
                  <p className="text-foreground/70">{feature.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      <Separator className="my-8 bg-primary/20" />
      <NewsletterSignup />
    </div>
  );
}
